services:
  - type: web
    name: cow-and-buffalo-recognition
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_SECRET_KEY
        generateValue: true
